### ISSUE TITLE
Ingestor to handle input data from multiple sensors, machines

### ISSUE THREAD

**Issue by AlexanderTheGrape** [se761group2/industry-4#43]
As a user, 
I want to see real-time data from all the machines (that I have access to),
So that I can monitor their condition

**Acceptance Criteria**

 - Ingestor is in the form of a Firebase Function (covered by #59) 
 - Ingestor can take the machineID and sensorID as input alongside data
 - Data is stored under the correct sensor in Firestore

**Is your feature request related to a problem? Please describe.**
The Ingestor currently reads the example data files and puts the data into Firestore as dummy data for a single sensor

**Describe the solution you'd like**
The Ingestor should be able to accept a POST with a data file as the body. It parses the file and calculates RMS and attaches a timestamp (already implemented). The difference is that it now takes in a machineID and sensorID that the data should be associated with.

**Describe alternatives you've considered**
There is an alternative approach we could take - wherever the data is sourced from (someone's PC, another server, IoT devices) they could run a script that looks a lot like the current Ingestor script. That is, it parses the files locally, calculates RMS, and uses the Firebase SDK to upload to Firestore. This would create a hard dependency between wherever they run the script and Firestore. If we provide an HTTP endpoint instead, this creates a very tech-agnostic interface with our application.

**Additional context**

**Comment by margeobur** [comment]
## To implement this 

First read my PR #67 that closes #59 - that will give you an idea of what the Ingestor looks like now and introduces the background for getting it working fully with different sensors.

Then, here's what you'll need to do:

- write code to store/fetch the ThresholdDetectionState in a Firestore document in a new top-level collection 
  - you can have one of these documents per sensor (remember we now have the machineID and sensorID readily available)
- fetch the ThresholdDetectionState from Firestore before you use it
- store it when you're done
- ezpz
- P.S. if you don't need to use the full RMS history (which could go back a long time) - maybe check the size of the rms values array and limit it to a certain size before you put it back into firestore (remove the first element, so that you effectively keep a rolling window of values). Value for that size can be quite large, but pick something that seems sensible based on what you know
